PreCommit:
  RuboCop:
    enabled: true
    required_executable: 'rubocop'
    command: ['bundle', 'exec', 'rubocop']
  
  RSpec:
    enabled: false
    description: 'Run RSpec tests'
    command: ['bundle', 'exec', 'rspec']

PrePush:
  Brakeman:
    enabled: true
    required_executable: 'brakeman'
    command: ['bundle', 'exec', 'brakeman', '-q']
  
  BundleAudit:
    enabled: false  # Disabled due to argument passing issues with git hooks
    description: 'Check for security vulnerabilities in dependencies'
    required_executable: 'bundler-audit'

